spring:
    application:
        name: api-gateway
    cloud:
       compatibility-verifier:
          enabled: false
       gateway:
          routes:
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
#            - id: discovery-server
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/web
#              filters:
#                - SetPath=/
#            - id: discovery-server-static
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/**

#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka
